# Generated by Django 4.1.7 on 2023-02-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_students_adminuser_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="Contact",
            field=models.BigIntegerField(default=0),
        ),
    ]
